INSERT INTO vets (first_name, last_name) SELECT 'James', 'Carter' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=1);
INSERT INTO vets (first_name, last_name) SELECT 'Helen', 'Leary' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=2);
INSERT INTO vets (first_name, last_name) SELECT 'Linda', 'Douglas' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=3);
INSERT INTO vets (first_name, last_name) SELECT 'Rafael', 'Ortega' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=4);
INSERT INTO vets (first_name, last_name) SELECT 'Henry', 'Stevens' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=5);
INSERT INTO vets (first_name, last_name) SELECT 'Sharon', 'Jenkins' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=6);

INSERT INTO specialties (name) SELECT 'radiology' WHERE NOT EXISTS (SELECT * FROM specialties WHERE name='radiology');
INSERT INTO specialties (name) SELECT 'surgery' WHERE NOT EXISTS (SELECT * FROM specialties WHERE name='surgery'); 
INSERT INTO specialties (name) SELECT 'dentistry' WHERE NOT EXISTS (SELECT * FROM specialties WHERE name='dentistry');

INSERT INTO vet_specialties VALUES (2, 1) ON CONFLICT (vet_id, specialty_id) DO NOTHING;
INSERT INTO vet_specialties VALUES (3, 2) ON CONFLICT (vet_id, specialty_id) DO NOTHING;
INSERT INTO vet_specialties VALUES (3, 3) ON CONFLICT (vet_id, specialty_id) DO NOTHING;
INSERT INTO vet_specialties VALUES (4, 2) ON CONFLICT (vet_id, specialty_id) DO NOTHING;
INSERT INTO vet_specialties VALUES (5, 1) ON CONFLICT (vet_id, specialty_id) DO NOTHING;

INSERT INTO types (name) SELECT 'cat' WHERE NOT EXISTS (SELECT * FROM types WHERE name='cat');
INSERT INTO types (name) SELECT 'dog' WHERE NOT EXISTS (SELECT * FROM types WHERE name='dog');
INSERT INTO types (name) SELECT 'lizard' WHERE NOT EXISTS (SELECT * FROM types WHERE name='lizard');
INSERT INTO types (name) SELECT 'snake' WHERE NOT EXISTS (SELECT * FROM types WHERE name='snake');
INSERT INTO types (name) SELECT 'bird' WHERE NOT EXISTS (SELECT * FROM types WHERE name='bird');
INSERT INTO types (name) SELECT 'hamster' WHERE NOT EXISTS (SELECT * FROM types WHERE name='hamster');

INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'George', 'Franklin', '110 W. Liberty St.', 'Madison', '6085551023' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=1);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Betty', 'Davis', '638 Cardinal Ave.', 'Sun Prairie', '6085551749' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=2);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Eduardo', 'Rodriquez', '2693 Commerce St.', 'McFarland', '6085558763' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=3);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Harold', 'Davis', '563 Friendly St.', 'Windsor', '6085553198' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=4);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Peter', 'McTavish', '2387 S. Fair Way', 'Madison', '6085552765' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=5);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Jean', 'Coleman', '105 N. Lake St.', 'Monona', '6085552654' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=6);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Jeff', 'Black', '1450 Oak Blvd.', 'Monona', '6085555387' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=7);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Maria', 'Escobito', '345 Maple St.', 'Madison', '6085557683' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=8);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'David', 'Schroeder', '2749 Blackhawk Trail', 'Madison', '6085559435' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=9);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Carlos', 'Estaban', '2335 Independence La.', 'Waunakee', '6085555487' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=10);

INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Leo', '2000-09-07', 1, 1 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=1);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Basil', '2002-08-06', 6, 2 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=2);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Rosy', '2001-04-17', 2, 3 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=3);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Jewel', '2000-03-07', 2, 3 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=4);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Iggy', '2000-11-30', 3, 4 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=5);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'George', '2000-01-20', 4, 5 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=6);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Samantha', '1995-09-04', 1, 6 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=7);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Max', '1995-09-04', 1, 6 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=8);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Lucky', '1999-08-06', 5, 7 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=9);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Mulligan', '1997-02-24', 2, 8 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=10);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Freddy', '2000-03-09', 5, 9 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=11);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Lucky', '2000-06-24', 2, 10 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=12);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Sly', '2002-06-08', 1, 10 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=13);

INSERT INTO visits (pet_id, visit_date, description) SELECT 7, '2010-03-04', 'rabies shot' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=1);
INSERT INTO visits (pet_id, visit_date, description) SELECT 8, '2011-03-04', 'rabies shot' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=2);
INSERT INTO visits (pet_id, visit_date, description) SELECT 8, '2009-06-04', 'neutered' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=3);
INSERT INTO visits (pet_id, visit_date, description) SELECT 7, '2008-09-04', 'spayed' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=4);

INSERT INTO featured_dogs (name, breed, age, description, rotation_index) SELECT 'Buddy', 'Golden Retriever', 3, 'Buddy loves fetch and swimming. He is the friendliest dog in the park!', 0 WHERE NOT EXISTS (SELECT * FROM featured_dogs WHERE rotation_index=0);
INSERT INTO featured_dogs (name, breed, age, description, rotation_index) SELECT 'Bella', 'Labrador Retriever', 2, 'Bella is gentle, patient, and great with children of all ages.', 1 WHERE NOT EXISTS (SELECT * FROM featured_dogs WHERE rotation_index=1);
INSERT INTO featured_dogs (name, breed, age, description, rotation_index) SELECT 'Max', 'German Shepherd', 4, 'Max is loyal, brave, and loves learning new tricks every day.', 2 WHERE NOT EXISTS (SELECT * FROM featured_dogs WHERE rotation_index=2);
INSERT INTO featured_dogs (name, breed, age, description, rotation_index) SELECT 'Luna', 'Siberian Husky', 1, 'Luna has striking blue eyes and boundless energy on every trail.', 3 WHERE NOT EXISTS (SELECT * FROM featured_dogs WHERE rotation_index=3);
INSERT INTO featured_dogs (name, breed, age, description, rotation_index) SELECT 'Charlie', 'Beagle', 5, 'Charlie has an incredible nose and a howl that wins hearts.', 4 WHERE NOT EXISTS (SELECT * FROM featured_dogs WHERE rotation_index=4);
INSERT INTO featured_dogs (name, breed, age, description, rotation_index) SELECT 'Daisy', 'French Bulldog', 3, 'Daisy is compact, charming, and loves lounging on the sofa.', 5 WHERE NOT EXISTS (SELECT * FROM featured_dogs WHERE rotation_index=5);
INSERT INTO featured_dogs (name, breed, age, description, rotation_index) SELECT 'Rocky', 'Rottweiler', 6, 'Rocky is a gentle giant who is endlessly devoted to his family.', 6 WHERE NOT EXISTS (SELECT * FROM featured_dogs WHERE rotation_index=6);
INSERT INTO featured_dogs (name, breed, age, description, rotation_index) SELECT 'Molly', 'Cocker Spaniel', 2, 'Molly has silky ears and an irresistible smile for everyone.', 7 WHERE NOT EXISTS (SELECT * FROM featured_dogs WHERE rotation_index=7);
INSERT INTO featured_dogs (name, breed, age, description, rotation_index) SELECT 'Bear', 'Bernese Mountain Dog', 4, 'Bear is calm, fluffy, and the ultimate cuddle companion.', 8 WHERE NOT EXISTS (SELECT * FROM featured_dogs WHERE rotation_index=8);
INSERT INTO featured_dogs (name, breed, age, description, rotation_index) SELECT 'Coco', 'Poodle', 3, 'Coco is clever, curly-coated, and always ready to perform.', 9 WHERE NOT EXISTS (SELECT * FROM featured_dogs WHERE rotation_index=9);
INSERT INTO featured_dogs (name, breed, age, description, rotation_index) SELECT 'Duke', 'Doberman Pinscher', 5, 'Duke is sleek, alert, and fiercely loyal to those he loves.', 10 WHERE NOT EXISTS (SELECT * FROM featured_dogs WHERE rotation_index=10);
INSERT INTO featured_dogs (name, breed, age, description, rotation_index) SELECT 'Rosie', 'Border Collie', 2, 'Rosie is a lightning-fast herder with an unstoppable work ethic.', 11 WHERE NOT EXISTS (SELECT * FROM featured_dogs WHERE rotation_index=11);

INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 1, 'https://placedog.net/640/480?id=1', 'Buddy in the park', 1, 204800, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=1 AND display_order=1);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 1, 'https://placedog.net/640/480?id=2', 'Buddy fetching the ball', 2, 183200, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=1 AND display_order=2);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 1, 'https://placedog.net/640/480?id=3', 'Buddy at the beach', 3, 220000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=1 AND display_order=3);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 2, 'https://placedog.net/640/480?id=4', 'Bella playing with kids', 1, 198400, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=2 AND display_order=1);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 2, 'https://placedog.net/640/480?id=5', 'Bella in the garden', 2, 175000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=2 AND display_order=2);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 2, 'https://placedog.net/640/480?id=6', 'Bella portrait', 3, 195000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=2 AND display_order=3);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 2, 'https://placedog.net/640/480?id=7', 'Bella on a walk', 4, 210000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=2 AND display_order=4);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 3, 'https://placedog.net/640/480?id=8', 'Max on patrol', 1, 212000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=3 AND display_order=1);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 3, 'https://placedog.net/640/480?id=9', 'Max learning tricks', 2, 190000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=3 AND display_order=2);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 3, 'https://placedog.net/640/480?id=10', 'Max resting', 3, 200000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=3 AND display_order=3);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 4, 'https://placedog.net/640/480?id=11', 'Luna on a hike', 1, 225000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=4 AND display_order=1);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 4, 'https://placedog.net/640/480?id=12', 'Luna in the snow', 2, 235000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=4 AND display_order=2);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 4, 'https://placedog.net/640/480?id=13', 'Luna close-up', 3, 218000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=4 AND display_order=3);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 4, 'https://placedog.net/640/480?id=14', 'Luna playing', 4, 205000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=4 AND display_order=4);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 4, 'https://placedog.net/640/480?id=15', 'Luna at sunset', 5, 230000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=4 AND display_order=5);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 5, 'https://placedog.net/640/480?id=16', 'Charlie sniffing around', 1, 192000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=5 AND display_order=1);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 5, 'https://placedog.net/640/480?id=17', 'Charlie howling', 2, 188000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=5 AND display_order=2);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 5, 'https://placedog.net/640/480?id=18', 'Charlie portrait', 3, 197000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=5 AND display_order=3);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 6, 'https://placedog.net/640/480?id=19', 'Daisy on the sofa', 1, 176000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=6 AND display_order=1);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 6, 'https://placedog.net/640/480?id=20', 'Daisy in a sweater', 2, 184000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=6 AND display_order=2);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 6, 'https://placedog.net/640/480?id=21', 'Daisy portrait', 3, 179000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=6 AND display_order=3);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 6, 'https://placedog.net/640/480?id=22', 'Daisy at the park', 4, 190000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=6 AND display_order=4);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 7, 'https://placedog.net/640/480?id=23', 'Rocky at home', 1, 240000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=7 AND display_order=1);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 7, 'https://placedog.net/640/480?id=24', 'Rocky playing', 2, 232000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=7 AND display_order=2);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 7, 'https://placedog.net/640/480?id=25', 'Rocky portrait', 3, 228000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=7 AND display_order=3);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 8, 'https://placedog.net/640/480?id=26', 'Molly portrait', 1, 186000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=8 AND display_order=1);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 8, 'https://placedog.net/640/480?id=27', 'Molly running', 2, 193000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=8 AND display_order=2);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 8, 'https://placedog.net/640/480?id=28', 'Molly in the garden', 3, 200000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=8 AND display_order=3);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 8, 'https://placedog.net/640/480?id=29', 'Molly napping', 4, 175000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=8 AND display_order=4);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 9, 'https://placedog.net/640/480?id=30', 'Bear cuddling', 1, 255000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=9 AND display_order=1);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 9, 'https://placedog.net/640/480?id=31', 'Bear in the mountains', 2, 260000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=9 AND display_order=2);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 9, 'https://placedog.net/640/480?id=32', 'Bear portrait', 3, 248000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=9 AND display_order=3);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 10, 'https://placedog.net/640/480?id=33', 'Coco performing', 1, 185000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=10 AND display_order=1);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 10, 'https://placedog.net/640/480?id=34', 'Coco portrait', 2, 178000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=10 AND display_order=2);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 10, 'https://placedog.net/640/480?id=35', 'Coco playing', 3, 192000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=10 AND display_order=3);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 10, 'https://placedog.net/640/480?id=36', 'Coco in the park', 4, 196000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=10 AND display_order=4);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 11, 'https://placedog.net/640/480?id=37', 'Duke on guard', 1, 222000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=11 AND display_order=1);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 11, 'https://placedog.net/640/480?id=38', 'Duke portrait', 2, 215000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=11 AND display_order=2);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 11, 'https://placedog.net/640/480?id=39', 'Duke with family', 3, 230000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=11 AND display_order=3);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 11, 'https://placedog.net/640/480?id=40', 'Duke running', 4, 218000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=11 AND display_order=4);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 11, 'https://placedog.net/640/480?id=41', 'Duke resting', 5, 210000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=11 AND display_order=5);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 12, 'https://placedog.net/640/480?id=42', 'Rosie herding', 1, 202000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=12 AND display_order=1);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 12, 'https://placedog.net/640/480?id=43', 'Rosie portrait', 2, 195000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=12 AND display_order=2);
INSERT INTO dog_photos (dog_id, photo_url, caption, display_order, file_size, file_type) SELECT 12, 'https://placedog.net/640/480?id=44', 'Rosie in action', 3, 208000, 'jpg' WHERE NOT EXISTS (SELECT * FROM dog_photos WHERE dog_id=12 AND display_order=3);
