name: Dependabot auto-merge

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test-and-automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # o la tua versione

      - name: Build with Maven
        run: mvn clean verify --batch-mode

      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
